### ISSUE TITLE
New node-gdal binaries needed

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mapnik-omnivore#106]
`node-gdal` [update today](https://github.com/naturalatlas/node-gdal/commit/a70807be8397da00067b0389be4c98acba7937e4)

Appveyor isn't happy. Pinned mapnik-omnivore to node-gdal 0.4.3 in the meantime.

cc @BergWerkGIS

**Comment by BergWerkGIS** [comment]
I published node-gdal 0.4.4 for toolset 14.
Build, that failed before, ran thru: https://ci.appveyor.com/project/Mapbox/mapnik-omnivore/build/1.0.427
You can bump again.

**Comment by springmeyer** [comment]
\o/

**Comment by BergWerkGIS** [comment]
:smile:

**Comment by GretaCB** [comment]
Woo! Thanks Willy
