### ISSUE TITLE
appveyor 32 bit builds are failing

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-omnivore#114]
After #113 (upgrade to latest node-gdal) appveyor 32 bit builds are failing. These are unrelated to mapnik-omnivore and should not delay a release. However before this mapnik-om can be pulled into studio we'll need to fix this: https://github.com/mapbox/windows-builds/issues/46

**Comment by BergWerkGIS** [comment]
All green now:
https://ci.appveyor.com/project/Mapbox/mapnik-omnivore/history
