### ISSUE TITLE
Non-georeferenced TIFFs

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mapnik-omnivore#115]
Implement better error handling for TIFFs that return null when calling [`gdalDatasource.geotransform`](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/raster.js#L44). If the TIFF does not contain georef, [node-gdal will return null](https://github.com/naturalatlas/node-gdal/blob/master/src/gdal_dataset.cpp#L881-L887).

A TIFF with no georef could potentially have a neighboring World (.tfw) file that contains the georef data. 

cc @rclark @springmeyer

**Comment by rclark** [comment]
> a neighboring World (.tfw) file

:-1: on supporting this. One of the expectations in a lot of our use of mapnik-omnivore is that we're dealing with an entirely standalone file. Agree, though, that null handling could use some work.

**Comment by GretaCB** [comment]
Merged and deployed.
