### ISSUE TITLE
test more failure

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapnik-omnivore#12]
Just added coverage testing to this project - [istanbul wraps the code and figures out what ran](https://github.com/gotwarlost/istanbul), and [coveralls](https://coveralls.io/builds/927309) makes the result readable. It's 95% tested (yay!) - the things that aren't tested yet are basically edge cases:

Run `npm run coverage` to generate this locally - the local view is way more detailed than coveralls.

* [we need an invalid kml test fixture](https://coveralls.io/files/234104132#L367)
* [need a file that this can't detect the type of](https://dl.dropboxusercontent.com/s/wtzjbbbjrinh1ts/2014-07-02%20at%206.40%20PM.png)
* need [non-parseable proj4 string](https://dl.dropboxusercontent.com/s/gy7d5hhm6x61r2d/2014-07-02%20at%206.42%20PM.png)
* and an invalid geojson file

The state of the art here is, afaik, just messing up files by hand to make them invalid. This should have a pretty good payoff, since invalid geospatial files are super common in the wild

**Comment by springmeyer** [comment]
This was done. We are now at 95%. Lets create new tickets for any more actionable holes.
