### ISSUE TITLE
Raster tiling resolution breaks

### ISSUE THREAD

**Issue by dnomadb** [mapbox/mapnik-omnivore#133]
Currently mapnik-omnivore decides on a raster's `maxzoom` with [breaks at tile resolutions](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/utils.js#L88-L101). If the raster resolution is at all above this break, it "tiles up" to a higher maxzoom, effectively resulting in upsampled imagery at the  `maxzoom`. This is problematic for raster datasets that are "snapped" to mercator tile resolutions, as rounding errors in pixel size can result in effectively a 1 zoom jump.

Here's how it works now (just higher zooms):
```
             ___________________________________________________
             |         |         |         |         |         |
maxzoom     z14       z15       z16       z17       z18       z19
             |_________|_________|_________|_________|_________|
             |= = = = >|= = = = >|= = = = >|= = = = >|= = = = >|
threshhold  9.55      4.78      2.39      1.19      0.6       0.3
             :         :         :         :         :         :
tiled res   9.55      4.78      2.39      1.19      0.6       0.3
```

## Proposal

Instead of always rounding to the next higher zoom, set breaks in-between mercator tile resolution and round to the _closest_ zoom:
```
             ___________________________________________________
             |         |         |         |         |         |
maxzoom     z14       z15       z16       z17       z18       z19
             |_________|_________|_________|_________|_________|
             :<= =|= =>:<= =|= =>:<= =|= =>:<= =|= =>:<= =|= =>:
threshhold   :   7.17  :   3.58  :   1.79  :   0.9   :   0.45  :
             :         :         :         :         :         :
tiled res   9.55      4.78      2.39      1.19      0.6       0.3
```
This would remove these rounding errors, and limit resampling to at most half the difference between mercator zooms.

Integrating this as weighted snapping ([as I've been working on in](https://github.com/mapbox/colonel-mercator/blob/51fdc3af6ec8914f1c999085521400593e198b9e/lib/merc_res.js#L60-L71) `colonel-mercator`) would allow for flexibility in `maxzoom` selection. This is where any number between 0 (snap up) and 1 (snap down) is used to express where the threshold should be (here is 0.333):
```
             ___________________________________________________
             |         |         |         |         |         |
maxzoom     z14       z15       z16       z17       z18       z19
             |_________|_________|_________|_________|_________|
             :<= | = =>:<= | = =>:<= | = =>:<= | = =>:<= | = =>:
threshhold   :  7.37   :  3.18   :  1.59   :  0.8    :  0.4    :
             :         :         :         :         :         :
tiled res   9.55      4.78      2.39      1.19      0.6       0.3
```

@GretaCB @yhahn @perrygeo

**Comment by dnomadb** [comment]
@rclark integrated this into `unpacker`, and I ran a few datasets through on staging. The results are as expected:
For datasets with the following input pixel sizes, these maxzooms are created:

pixelSize | maxzoom
--- | ---
0.5688336976743196 | z18
0.5971642822264585 | z18
0.3981095214843056 | z19
0.6635878730329826 | z18

In visual form in regards to the old + new breaks:
```

               z17      z18      z19
                |        |        |
breaks@master 1.194    0.597    0.299
                :<|      :<|      |
breaks@res-so   0.904    0.452  0.299
0.56883---------:- ------:-|      :
                :        : |
maxzoom         :        [<|      :
0.59716---------:--------|        :
maxzoom         :        |        :
0.39811---------:--------:----|   :
maxzoom         :        :    |==>]
0.66359---------:------| :        :
maxzoom         :      |>]        :
                |        |        |
               z17      z18      z19
```

**Comment by springmeyer** [comment]
@dnomadb - curious where this effort stands?

**Comment by dnomadb** [comment]
Closed via https://github.com/mapbox/mapnik-omnivore/pull/134 @springmeyer - thx for bump!
