### ISSUE TITLE
Upgrade to node-gdal 0.9.1

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-omnivore#138]
New node-gdal is out using GDAL 2.0.2 with various bug fixes: notably no longer crashes on GPX files with the `<time>` element.

TODO:

  - [x] then tagging party to get all modules on node-gdal 0.9.x - mapnik-omnivore and friends.

```
 - bump `gdal` in: deps that depend on it:
   - `wmtiff`
   - `srs`
   - `wmshp`
   - `bytetiff`
 - bump deps that depend indirectly:
   - `preprocessorcerer`
   - `mapnik-omnivore`
 - bump `mapnik-omnivore` in:
   - `tilelive-omnivore`
   - `happytiff`
 - bump `tilelive-omnivore` in `mapbox-upload-validate`
 - bump `mapbox-upload-validate` and `tilelive-omnivore` in `mapbox-tile-copy`
```

**Comment by andrewgoodchild** [comment]
+1 on this.   I am having trouble installing node-gdal 0.8  on my machine as it fails when node-pre-gyp tries to bring in the dependencies it needs.  node-gdal 0.9.2 on the other hand installs without a hitch.

**Comment by GretaCB** [comment]
Done
