### ISSUE TITLE
pixel size calculation for ft, etc off

### ISSUE THREAD

**Issue by dnomadb** [mapbox/mapnik-omnivore#154]
@GretaCB @rclark 

Looking at: https://github.com/mapbox/mapnik-omnivore/blob/master/lib/utils.js#L55-L63

- If the unit is feet, say 1 foot
- This should be 0.3048 m
- But here, the math is 1 / 0.3048, which equals 3.280839895013123

It should be 1 * 0.3048, 0.3048.

Here's an example with a dataset in http://www.spatialreference.org/ref/epsg/3734/ + 0.333 `ft` resolution
```
» rio info /tmp/cuyahoga.tif | jq .res
[
  0.33333333,
  0.33333333
]
```
vs
```
 » digest /tmp/cuyahoga.tif | jq .raster.pixelSize
[
  1.0936132874015747,
  -1.0936132874015747
]
```
Warping this dataset to web mercator and re-running:
```
» rio info /tmp/cuyahogawm.tif | jq .res
[
  0.13539983354073065,
  0.13539983354073065
]
```
+
```
» digest /tmp/cuyahogawm.tif | jq .raster.pixelSize
[
  0.13539983354073065,
  -0.13539983354073065
]
```

The `digest ==> .raster.pixelSize` parameter returned _should_ be the pixelSize in m, correct?

**Comment by rclark** [comment]
:+1: we should have unit tests for these utils.js functions.

**Comment by dnomadb** [comment]
@rclark y, tests still pass when I fix the conversion  👀 

I'll add unit tests in https://github.com/mapbox/mapnik-omnivore/pull/155

**Comment by GretaCB** [comment]
> The digest ==> .raster.pixelSize parameter returned should be the pixelSize in m, correct?

yes, nice catch

**Comment by GretaCB** [comment]
So does this mean our pixel res detection/therefore raster zoom detection has been offset?

**Comment by dnomadb** [comment]
> So does this mean our pixel res detection/therefore raster zoom detection has been offset?

@GretaCB I think we are ok. Input resolutions in `m` are [untouched](https://github.com/mapbox/mapnik-omnivore/pull/155/files#diff-50e3aa130a4f97a42ee2cf111c7b1d9dR53) - and since [we `preprocessorcer` rasters to web-mercator](https://github.com/mapbox/unpacker/blob/9c9aad5d41e9f7ab964246081fcdd4b0b4c24055/bin/unpacker#L244) before `digest`ing, I think that we are in the clear
