### ISSUE TITLE
dependency: move to @mapbox/sphericalmercator

### ISSUE THREAD

**Issue by mcm-jyl** [mapbox/mapnik-omnivore#156]
the current version in the repository includes the @mapbox namespace change (@mapbox/mapnik-omnivore@8.2.0, good) but is still using the good old sphericalmercator, not @mapbox/sphericalmercator

**Comment by mapsam** [comment]
Thanks @mcm-jyl! This was resolved in https://github.com/mapbox/mapnik-omnivore/pull/165
