### ISSUE TITLE
Zoom levels are not computed consistently

### ISSUE THREAD

**Issue by kapadia** [mapbox/mapnik-omnivore#57]
@GretaCB 

@rclark and I found that `getMinMaxZoomGDAL` isn't computing zoom levels consistently between 2 images, despite both having the same spatial resolution.

I re-wrote the function to make use of a look up table. It cuts of the zoom level as soon as the given `pixelSize` exceeds the spatial resolution in the table.

Would you mind double checking this work to make sure I haven't stomped on something?

PR at https://github.com/mapbox/mapnik-omnivore/pull/56

**Comment by GretaCB** [comment]
@kapadia this looks good, I will do a final test and publish tomorrow. Woot!
