### ISSUE TITLE
Detection of TopoJSON vs GeoJSON

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-omnivore#59]
Omnivore should gain the ability to detect TopoJSON vs GeoJSON files.

Currently we are passing json to OGR and letting it figure out how to parse both of the data formats. But we need to move to Mapnik's native GeoJSON datasource (#58) for reading GeoJSON. Because it does not also read TopoJSON (instead a different Mapnik datasource called 'topojson' reads TopoJSON) we'll need to have mapnik-omnivore gain the ability to detect a json file as either GeoJSON or TopoJSON. Then we'll be able to dispatch to the correct Mapnik plugin.

So, currently for any json file we are using `'type':'ogr'`. But after #58 we'll use`'type':'geojson'` for GeoJSON and `'type':'topojson'` for TopoJSON.

**Comment by GretaCB** [comment]
Thanks @springmeyer , I currently have this logic and [tests](https://github.com/mapbox/mapnik-omnivore/blob/759eaa0aeb7c7dacf391ca313b41b6eeeef89191/test/datasource-processor.test.js#L156-L178) ready to go (from the summer). I didn't get a chance to test. 

I will just need to change the Mapnik datasource type.

**Comment by springmeyer** [comment]
Thanks @GretaCB - realizing this might be better over at https://github.com/mapbox/mapbox-file-sniff/issues/19? Also I just updated the description with a bit more detail.

**Comment by GretaCB** [comment]
This is now [implemented in mapbox-file-sniff](https://github.com/mapbox/mapbox-file-sniff/blob/master/index.js#L24-L38) and each has their own module and mapnik type in mapnik-omnivore https://github.com/mapbox/mapnik-omnivore/pull/84.
