### ISSUE TITLE
Missing packages, for future reference

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mapnik-omnivore#63]
Just FYI, had to unpublish a couple packages due to the wrong Semantic Version in the context of this zoom change. In addition, this change cascaded into a few other projects that also had to be unpublished (the packages that were relevant to the unpublished mapnik-omnivore packages).

If you run into install errors due to missing packages, this is why.

Needless to say, Semantic Versioning is SUPER important, and I have learned a hard lesson. Never again.

cc @rclark @kapadia

**Comment by kapadia** [comment]
Thanks for the note. Out of curiosity, which other projects were affected?

**Comment by GretaCB** [comment]
@kapadia Include packages were:
- `mapbox-upload-validate`
- `mapbox-tile-copy`
- `tilelive-omnivore`
- `mapbox-map-metadata`
