### ISSUE TITLE
Unhandled error with unprojected TIF

### ISSUE THREAD

**Issue by rclark** [mapbox/mapnik-omnivore#64]
If a tif comes through that 
- has a coordinate system defined, say epsg:4326
- doesn't have any georeferencing info

Then tools like `gdalinfo` and `rio info` will kinda lead you to believe that they're okay -- until you notice that the pixel dimensions are identical to the geographic extent. That is, one pixel = one degree, and the image is 3000 pixels wide.

Also, [mapnik-omnivore fails here](https://github.com/mapbox/mapnik-omnivore/blob/0931b7768a71dde5d5488632c6d57696adaefc00/lib/datasource-processor.js#L431) in an unhandled fashion, because `ds.geoTransform` was `null` to begin with.

I think we need some kind of check in here that georeferencing information is valid? Is the lack of a geotransform enough / unique to this situation?

cc @GretaCB @sgillies wonder what you guys think? I can provide a test fixture.

**Comment by sgillies** [comment]
@rclark I'd say that a GDAL geotransform of `[0.0, 1.0, 0.0, 0.0, 0.0, 1.0]` (what I get from any old unprojected PNG or JPEG with Rasterio) would be a red flag, yes. Origin at `0, 0`, pixel size of `1, 1` and `y` increasing *downward* indicate a raster with no georeferencing.

**Comment by GretaCB** [comment]
@rclark just fyi, going to add a validation check [here for [0, 1, 0, 0, 0, 1]](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasource-processor.js#L452)
