### ISSUE TITLE
Remove OGR Plugin error stopgap for layers

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mapnik-omnivore#66]
Obtaining layer names from an KML/geojson source used to be done [by parsing the error message](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasource-processor.js#L579-L591) returned from mapnik.

As of November 2014, node-gdal now allows for grabbing layer info. [See this for example](https://github.com/naturalatlas/mapnik-omnivore/blob/gdal-refactor/lib/digestors/ogr.js#L47-L98).

cc @springmeyer @rclark

**Comment by GretaCB** [comment]
Enabling this in the refactor at https://github.com/mapbox/mapnik-omnivore/pull/74

**Comment by springmeyer** [comment]
woot!

**Comment by GretaCB** [comment]
Currently implemented in refactor PR https://github.com/mapbox/mapnik-omnivore/pull/84
