### ISSUE TITLE
[bluesky?] Refactor into modules for each type of dataset

### ISSUE THREAD

**Issue by rclark** [mapbox/mapnik-omnivore#68]
Building modules that each deal with a specific type of file could really help this library be more approachable and maintainable. I'm imagining modules which all have methods like `getProjection` and `getExtent`, and a single `digest()` function that chooses the right module + strings together method calls to build a metadata object.

Most of the functions in the current implementation are like [getProjection](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasource-processor.js#L101) and while sounding generic, contain logic that branches based on filetype anyways.

Implementing this would make adding new features like [different mapnik datasource types for topojson and geojson](https://github.com/mapbox/mapnik-omnivore/issues/58) much more straightforward to implement. For example the mess I made in #67.

cc @GretaCB

**Comment by springmeyer** [comment]
:+1: refactoring this soon hopefully would help unblock #72

**Comment by GretaCB** [comment]
Refactor PR at https://github.com/mapbox/mapnik-omnivore/pull/84

**Comment by GretaCB** [comment]
Merged.
