### ISSUE TITLE
use mapbox-file-sniff

### ISSUE THREAD

**Issue by rclark** [mapbox/mapnik-omnivore#70]
We should be able to tear out [a bunch of this code](https://github.com/mapbox/mapnik-omnivore/blob/master/index.js#L52-L87) and put in a [mapbox-file-sniff](https://github.com/mapbox/mapbox-file-sniff) call.

**Comment by GretaCB** [comment]
:+1:

**Comment by GretaCB** [comment]
Setup in https://github.com/mapbox/mapnik-omnivore/pull/74
