### ISSUE TITLE
Insure that min/max zoom calculations are made on pixel dimensions in meters

### ISSUE THREAD

**Issue by rclark** [mapbox/mapnik-omnivore#75]
It appears that omnivore is basing its min/max zoom calculations on *whatever the pixel dimensions it finds are* but assuming that the units are meters.

I took a file in WGS84 (pixel dimensions are [ 0.0002709972254827934, 0.00027099722548279344 ] *degrees*) and omnivore told me to use z14-z20 -- 500k+ tiles to copy. I used `gdalwarp` to convert the file to spherical mercator (new dimensions [ 30.184065760088856, 30.184065760088856 ] in *meters*) and omnivore said z7-z13 -- 484 tiles to copy.

cc @kapadia

**Comment by kapadia** [comment]
Good catch @rclark. How about one of these:

 1. Compute the meter resolution within `getMinMaxZoomGDAL`
 2. Add this as a preprocess stage

**Comment by rclark** [comment]
> Compute the meter resolution within getMinMaxZoomGDAL

We should definitely do this. This is a current bug in omnivore and ought to get solved here. 

Also, yes, we'll be considering preprocessing steps elsewhere in tile-rendering pipelines.

**Comment by GretaCB** [comment]
@kapadia @rclark I wrote [a function](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasource-processor.js#L367-L380) back in the day to obtain the exact unit type of the source (but is no longer in use). Not sure if it helps at all.

**Comment by kapadia** [comment]
That's great @GretaCB. Very useful.

**Comment by rclark** [comment]
Fixed in #76
