### ISSUE TITLE
TypeError: Cannot call method 'next' of undefined

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapnik-omnivore#80]
It looks like @edenh tried to upload a GL stylesheet and we are trying to process it as if it were geojson.

```
Message: {"id":"a23ee4f0916060fa1a6c6494cda66596","owner":"edenhalperin","data":"edenhalperin.14b49096b0c","url":"https://tilestream-tilesets-production.s3.amazonaws.com/_pending/edenhalperin/09e4295c46a134f57588845b753d325e","parts":1,"part":0}
```

This results in the following crash inside mapnik-omnivore:

```
TypeError: Cannot call method 'next' of undefined
    at getDatasourceProperties (/usr/local/src/service-worker/node_modules/mapbox-upload-validate/node_modules/tilelive-omnivore/node_modules/mapnik-omnivore/lib/datasource-processor.js:578:38)
```

https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasource-processor.js#L578

We should make our validation stricter in https://github.com/mapbox/mapbox-upload-validate but also make this project fail a little more gracefully.

/cc @rclark @GretaCB

**Comment by GretaCB** [comment]
@willwhite @edenh do we want to support GL stylesheets in mapnik-omnivore? Or was this just a mistake upload? 

I can add some more validation in the meantime.

**Comment by edenh** [comment]
Totally a mistake. Better validation ticket: https://github.com/mapbox/mapbox-gl-online/issues/1130

I'll be more careful in the meantime about what files I use for testing.

**Comment by rclark** [comment]
We still clearly need [better identification of valid vs. invalid geojson](https://github.com/mapbox/mapnik-omnivore/issues/78#issuecomment-72374210), probably in mapbox-file-sniff.

**Comment by rclark** [comment]
While the symptoms are different, this cause of this failure is identical to https://github.com/mapbox/mapnik-omnivore/issues/78, so this is a duplicate ticket. Next actions are outlined in #78

**Comment by willwhite** [comment]
> I'll be more careful in the meantime about what files I use for testing.

Please continue to throw random stuff at the unpacker. It finds bugs like this so customers don't :)
