### ISSUE TITLE
jscs errors

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-omnivore#94]
I'm struggling to understand how to fix the jscs errors. I'm seeing them locally on OSX and on appveyor: https://ci.appveyor.com/project/Mapbox/mapnik-omnivore/build/1.0.386/job/spic72g2xl5dthkh#L122. Oddly travis seems happy.

It is unclear to me how to fix them:

```
Missing newline after closing curly brace at lib/raster.js :
   162 |    km: function(x) { return x / 1000; },
   163 |    'us-ft': function(x) { return x / 0.3048; },
   164 |    'us-mi': function(x) { return x / 1609.34; },
--------------------------------------------------------^
   165 |    'decimal degrees': function(x) { return x / 360 * circumference; }
   166 |  };
```

It almost looks like a jscs false positive.

**Comment by GretaCB** [comment]
Looks like possible invalid jscs dep, `esparse` ([updated 4 days ago](https://www.npmjs.com/package/jscs))?

**Comment by rclark** [comment]
Yeah see https://github.com/jscs-dev/node-jscs/commit/f58e11534037067bfe5b1d94fec949491dd73f51

It wants you to put newlines after each of those ending curly braces close a block. We should consider dropping the airbnb preset and writing our own list of style guidelines, or drop jscs, or something.

**Comment by springmeyer** [comment]
nothing more needed here
